import type { ParsedIssue } from '@codepilot/shared';
import type { LLMAdapter, CompletionResult } from '../llm/index.js';
import type { Plan, PatchResult } from './types.js';
import { logger } from '../utils/logger.js';

const MAX_GENERATE_RETRIES = 2;

const SYSTEM_PROMPT = `You are CodePilot's code generation module. Given a GitHub issue, relevant code context, and a solution plan, generate a unified diff patch that resolves the issue.

Rules:
- Output ONLY the unified diff (patch format). No explanations before or after.
- Use standard unified diff format with --- a/ and +++ b/ prefixes.
- Include proper @@ hunk headers.
- After the diff, add a line "---EXPLANATION---" followed by a brief explanation of what the patch does.
- After the explanation, add a line "---FILES---" followed by a comma-separated list of changed files.

Example output format:
--- a/src/utils.ts
+++ b/src/utils.ts
@@ -10,3 +10,5 @@ function helper() {
   return value;
 }
+
+export function newHelper() { return true; }
---EXPLANATION---
Added newHelper function to utils module.
---FILES---
src/utils.ts`;

function buildUserPrompt(
  issue: ParsedIssue,
  codeContext: string,
  plan: Plan,
  previousError?: string,
): string {
  const parts = [
    `## GitHub Issue #${issue.number}: ${issue.title}`,
    '',
    issue.body,
    '',
    '## Solution Plan',
    `Approach: ${plan.approach}`,
    '',
    ...plan.steps.map((s, i) => `${i + 1}. [${s.action}] ${s.description} (files: ${s.files.join(', ')})`),
    '',
    '## Relevant Code Context',
    codeContext || 'No relevant code found.',
  ];

  if (previousError) {
    parts.push('', `## Previous Attempt Failed`, `Error: ${previousError}`, 'Please fix the patch and try again.');
  }

  return parts.join('\n');
}

function extractDiff(text: string): string | null {
  const explanationMarker = '---EXPLANATION---';
  const explanationIdx = text.indexOf(explanationMarker);

  let diffSection: string;
  if (explanationIdx !== -1) {
    diffSection = text.slice(0, explanationIdx).trim();
  } else {
    diffSection = text.trim();
  }

  // Try extracting from code fences first
  const fencedMatch = diffSection.match(/```(?:diff)?\s*\n?([\s\S]*?)```/);
  if (fencedMatch?.[1]) {
    diffSection = fencedMatch[1].trim();
  }

  // Validate it looks like a diff
  if (diffSection.includes('--- a/') || diffSection.includes('diff --git')) {
    return diffSection;
  }

  return null;
}

function extractExplanation(text: string): string {
  const explanationMarker = '---EXPLANATION---';
  const filesMarker = '---FILES---';

  const explanationIdx = text.indexOf(explanationMarker);
  if (explanationIdx === -1) {
    return 'Patch generated by CodePilot.';
  }

  const afterExplanation = text.slice(explanationIdx + explanationMarker.length);
  const filesIdx = afterExplanation.indexOf(filesMarker);
  if (filesIdx !== -1) {
    return afterExplanation.slice(0, filesIdx).trim();
  }

  return afterExplanation.trim();
}

function extractFiles(text: string): readonly string[] {
  const filesMarker = '---FILES---';
  const filesIdx = text.indexOf(filesMarker);
  if (filesIdx === -1) {
    return [];
  }

  const afterFiles = text.slice(filesIdx + filesMarker.length).trim();
  return afterFiles
    .split(',')
    .map((f) => f.trim())
    .filter((f) => f.length > 0);
}

/** Generate a unified diff patch for a given issue and plan */
export async function generatePatch(
  issue: ParsedIssue,
  codeContext: string,
  plan: Plan,
  llm: LLMAdapter,
  previousError?: string,
): Promise<PatchResult> {
  const log = logger.child({ module: 'generator', issueNumber: issue.number });

  let lastError = previousError;

  for (let attempt = 0; attempt <= MAX_GENERATE_RETRIES; attempt++) {
    log.info({ attempt }, 'Generating patch');

    const userPrompt = buildUserPrompt(issue, codeContext, plan, lastError);

    let completion: CompletionResult;
    try {
      completion = await llm.complete({
        systemPrompt: SYSTEM_PROMPT,
        messages: [{ role: 'user', content: userPrompt }],
        temperature: 0.1,
        maxTokens: 8192,
      });
    } catch (error) {
      log.error({ error, attempt }, 'LLM completion failed during generation');
      throw error;
    }

    const diff = extractDiff(completion.content);

    if (diff) {
      const explanation = extractExplanation(completion.content);
      const filesChanged = extractFiles(completion.content);

      const result: PatchResult = {
        patch: diff,
        explanation,
        filesChanged: filesChanged.length > 0 ? filesChanged : [...plan.estimatedFiles],
      };

      log.info(
        { filesChanged: result.filesChanged.length, patchLength: diff.length },
        'Patch generated successfully',
      );
      return result;
    }

    lastError = 'Generated output did not contain a valid unified diff. Please output a proper unified diff with --- a/ and +++ b/ prefixes.';
    log.warn({ attempt }, 'Invalid diff output, retrying');
  }

  const finalError = `Failed to generate valid patch after ${MAX_GENERATE_RETRIES + 1} attempts`;
  log.error(finalError);
  throw new GeneratorError(finalError, 'invalid_diff');
}

/** Custom error class for generator errors */
export class GeneratorError extends Error {
  constructor(
    message: string,
    public readonly code: 'invalid_diff' | 'llm_error',
  ) {
    super(message);
    this.name = 'GeneratorError';
  }
}
