import type { AgentResult } from '@codepilot/shared';
import type { LLMAdapter } from '../llm/index.js';
import type { VectorStore } from '../indexer/store.js';
import type { SandboxManager } from '../sandbox/index.js';
import type { Octokit } from '@octokit/rest';

/** Configuration for an agent run */
export interface AgentConfig {
  readonly llm: LLMAdapter;
  readonly vectorStore: VectorStore;
  readonly sandboxManager: SandboxManager;
  readonly octokit: Octokit;
  readonly maxRetries: number;
  readonly maxContextTokens: number;
}

/** A single step in the agent execution */
export interface AgentStep {
  readonly name: string;
  readonly status: 'running' | 'success' | 'failed';
  readonly durationMs: number;
  readonly details?: string;
}

/** Full record of an agent run */
export interface AgentRun {
  readonly id: string;
  readonly issueNumber: number;
  readonly steps: readonly AgentStep[];
  readonly result: AgentResult;
  readonly startedAt: Date;
  readonly completedAt?: Date;
}

/** A step in the solution plan */
export interface PlanStep {
  readonly description: string;
  readonly files: readonly string[];
  readonly action: 'modify' | 'create' | 'delete';
}

/** Solution plan generated by the planner */
export interface Plan {
  readonly summary: string;
  readonly steps: readonly PlanStep[];
  readonly estimatedFiles: readonly string[];
  readonly approach: string;
}

/** Result of a patch generation */
export interface PatchResult {
  readonly patch: string;
  readonly explanation: string;
  readonly filesChanged: readonly string[];
}

/** A single issue found during critic review */
export interface CriticIssue {
  readonly severity: 'error' | 'warning' | 'info';
  readonly description: string;
  readonly file?: string;
  readonly line?: number;
}

/** Result of a critic review */
export interface CriticResult {
  readonly score: number;
  readonly passed: boolean;
  readonly feedback: string;
  readonly issues: readonly CriticIssue[];
}

/** Result of running tests in sandbox */
export interface RunResult {
  readonly patchApplied: boolean;
  readonly testsRan: boolean;
  readonly testsPassed: boolean;
  readonly output: string;
  readonly error?: string;
}

export type { AgentResult };
